---
# Author: Shravan

- hosts: all
  gather_facts: no
  remote_user: '{{ ansible_ssh_user }}'

  tasks:

    - name: Copy cert file to /tmp
      copy:
        src: "/home/sdasari/ssl-cert-check"
        dest: "/tmp"
        mode: '0755'

    - name:  get cert info for app7
      when: inventory_hostname in groups.app7cert
      command: sh ssl-cert-check -c {{certdir}}/dev7cops.crt
      register: app7c

    - name:  get cert info for app1cert
      when: inventory_hostname in groups.app1cert
      command: sh ssl-cert-check -c {{certdir}}/devops1c.crt
      register: app1c

    # - lineinfile:
    #     create: yes
    #     path: "{{workspace}}/results.txt"
    #     line: "{{op.stdout}}"
    #     insertbefore: BOF
    #   when: not(op|skipped)
    #   delegate_to: localhost
